### ISSUE TITLE
Problem example 8

### ISSUE THREAD

**Issue by LisandroCanalLD** [tomik23/leaflet-examples#30]
Hello Tomik23.
I found a problem in the example 8 "controlling different groups of markers".
when displaying the markets, they all have the same Popup. I have not been able to fix it.
Besr¿t Wishes, Canal Lisandro.

**Comment by LisandroCanalLD** [comment]
I managed to solve it by changing

for (let i = 0; i < pointsA.length; i++) {
  marker = L.marker([pointsA[i][0], pointsA[i][1]]);
  pA.addLayer(marker).bindPopup(pointsA[i][2]);
}

for

for (let i = 0; i < pointsA.length; i++) {
  marker = L.marker([pointsA[i][0], pointsA[i][1]])
  .setPopupContent(pointsA[i][2])
  .bindPopup(pointsA[i][2]);
  pA.addLayer(marker).setPopupContent(pointsB[i][2]);
}

**Comment by tomik23** [comment]
A slight oversight ;)
Instead of `.binPopup(pointA[i][2];` add to marker was added to layer ;)

**Comment by tomik23** [comment]
I will correct it when adding the next example ;)
Thanks for your comments.
