### ISSUE TITLE
Small list of improvements

### ISSUE THREAD

**Issue by krijnsent** [tomik23/leaflet-examples#6]
Nice examples! Some improvements:
-typo: add move and delete marker -> text on the pop-up of the marker is "delte marker" -> "delete marker"
-typo: page title (in bar): "EXMAPLES", should be EXAMPLES :)
-coordinates of the visible map -> does only work with move, not with change of Zoom (you might want to add that)
-geocoding: try "Utrecht" -> the first 3 results seem the same, but the first is the city, the second the municipality and the third the province, so you might want to add that in the description.

And some suggestions/ideas:
-add a circlemarker example
-a circlemarker example with a fill color, based on data (e.g. "high"-> red fill, "medium"-> yellow fill, etc.).
For inspiration: https://krijnsent.github.io/muralsonamap/ (use the menu for a filter/coloring)

**Comment by tomik23** [comment]
Thanks, well caught ;)
What I can do, I will quickly improve.
As for geocoding, unfortunately, but with such a request, the nominatim returns the result, look at [link](https://nominatim.openstreetmap.org/search?format=geojson&limit=5&q=Utrecht), of course, you can change the query or even filter the names in the script itself.

And thanks for the suggestions, I will consider them :)

**Comment by krijnsent** [comment]
The geocoding can be a bit more advanced, try e.g.:
https://nominatim.openstreetmap.org/search.php?format=geojson&limit=3&addressdetails=1&q=utrecht
That gives a type (administrative) and the lowest level of  address (suburb / state, etc) is the type of that region.

**Comment by tomik23** [comment]
Yes, I know, but these are examples of using _[autosuggest](https://github.com/tomik23/autosuggest)_ not learning nominatim ;)
